### PR TITLE
schedule updated and added

### PR DESCRIPTION
**Pull request by impedaka**

### CODE REVIEW

**Comment by cabbagecabbagecabbage** [comment]
comment out the workshops for now, but you can keep the intro to python on there


> Hackenger Hunt 1

should be

> Scavenger Hunt


For now, put "Subject to change. More events and descriptions will be added as we finalize the details." instead of "Click on the activities for more info!"


Make check-in and check-out a different colour than blue.

**Comment by cabbagecabbagecabbage** [comment]
either @impedaka or @HACKERALERT 

can you make the side bar go under the schedule? I don't want it to interfere with people trying to read it

**Comment by HACKERALERT** [comment]
Sure I can do it. I'll wait for the current PR to be merged before working on it to prevent any conflicts.

**Comment by cabbagecabbagecabbage** [comment]
change the colours of the second day check-in and check-out as well, same colour as first day

**Comment by impedaka** [comment]
> change the colours of the second day check-in and check-out as well, same colour as first day

@cabbagecabbagecabbage fixed

**Comment by cabbagecabbagecabbage** [comment]
@HACKERALERT

**Pull request merged**
